# Common vars
availability_zone: melbourne-qh2-uom


# Volume
volumes:
  - vol_name: CCC-volume1
    vol_size: 50
  - vol_name: CCC-volume2
    vol_size: 50
  - vol_name: CCC-volume3
    vol_size: 50
  - vol_name: CCC-volume4
    vol_size: 50


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: internal_icmp
    description: "Demo security group for icmp"
    protocol: icmp
    port_range_min: 0
    port_range_max: 255
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: internal_tcp
    description: "Demo security group for tcp"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: internal_udp
    description: "Demo security group for udp"
    protocol: udp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  


# instance
instances:
  - instance_name: CCC-haikuan
    instance_image: 37788d15-12bd-488c-b15e-903d43eae051
    instance_key_name: CCC-keypair
    instance_flavor: uom.general.2c8g
    # 2
  - instance_name: CCC-haikuan
    instance_image: 37788d15-12bd-488c-b15e-903d43eae051
    instance_key_name: CCC-keypair
    instance_flavor: uom.general.2c8g
    # 3
  - instance_name: CCC-haikuan
    instance_image: 37788d15-12bd-488c-b15e-903d43eae051
    instance_key_name: CCC-keypair
    instance_flavor: uom.general.2c8g
    # 4
  - instance_name: CCC-haikuan
    instance_image: 37788d15-12bd-488c-b15e-903d43eae051
    instance_key_name: CCC-keypair
    instance_flavor: uom.general.2c8g
